---
# tasks file for task4-role
- name: Install httpd
  yum:
    name: httpd
    state: present
- name: Start and enable httpd
  service:
    name: httpd
    state: started
    enabled: true
- name: install vhost config file
  template: 
    src: templates/vhost.conf.j2
    dest: /etc/httpd/conf.d/vhost.conf 
  notify: 
  - restart httpd
