---
- name: Implementing a Playbook to Manage Software
  hosts: all
  vars_files:
  - vars/all_vars
  tasks:
  - name: shell
    shell: |
      cat /etc/yum.repos.d/task2-repos.repo
    register: display
  - name: debug
    debug: 
      var: display
  - name: install yum repository
    yum_repository:
      name: task2-repo
      description: RHCE8 repo
      file: task2-repos
      baseurl: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
      gpgcheck: no
      state: present
  - name: install package - {{ package }}
    yum:
      name: "{{ package }}"
      state: present
  - name: get information about all installed packages
    package_facts:
      manager: auto
  - name: display package information about {{ package }}
    debug: 
      var: ansible_facts.packages.package 
    when: package in ansible_facts.packages
  - name: Verify
    shell: |
      echo ''
      echo 'yum repo list'
      yum repo list
      echo ''
      echo 'ls -ltr /etc/yum.repos.d/'
      ls -ltr /etc/yum.repos.d/
      echo ''
      echo 'cat /etc/yum.repos.d/task2-repo'
      cat /etc/yum.repos.d/task2-repo
     
